### ISSUE TITLE
[2pt] UI: schema validation errors are not shown

### ISSUE THREAD

**Issue by HustonMmmavr** [tarantool/cartridge#1082]
Steps to reproduce:

1. Insert this schema `/admin/cluster/schema`

```yml
spaces:
  test_space:
    # engine must be memtx or vinyl
    engine: engine 
    is_local: false
    temporary: false
    format:
    - name: x
      type: unsigned
      is_nullable: false
    indexes:
    - name: pk
      type: TREE
      unique: true
      parts:
      - path: x
        is_nullable: false
        type: unsigned
```
2. Run validate. As a result there is no error shown, but response contains it

![Screenshot from 2020-10-05 12-48-34](https://user-images.githubusercontent.com/25960394/95064987-1f876880-0709-11eb-9a65-a4e216f70467.png)
