### ISSUE TITLE
[2pt] Enhance UX of zone_distances configuration

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1096]
Related to #1086 

After a user configures zones he should also specify distances matrix. It's format isn't obvious so we should do our best to help.

Proposed solution

Let's generate `zone_distances.yml` section automatically. When a user specifies new zone, we could render the section appropriately and fill it with NULLs.

Suppose we already have `zone_distances.yml`:

```yaml
z1: {z1: 0, z2: 10}
z2: {z1: 10, z2: 0}
```

and then user makes a request:

```graphql
mutation { cluster{
  edit_topology(servers: [{uuid: "..." zone: "z3"}]){}
} }
```

It not only modifies `server.zone` property, but also updates zone_distances as follows:

```yaml
z1: {z1: 0, z2: 10, z3: null}
z2: {z1: 10, z2: 0, z3: null}
z3: {z1: null, z2: null, z3: 0}
```
