### ISSUE TITLE
GraphQL API errors

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#125]
In GitLab by @v.tyubek on Jun 24, 2019, 14:09

### Problem statement

Errors should by easily identifiable by machine. Example use case: cluster is deployed via ansible. Ansible should distinguish ```error```, ```nothing changed```, ```changed ok``` states. When issuing join_instance one should write ansible checks like this one: 

```yaml
until: "'data' in result.json or ('errors' in result.json and 'already joined' in result.content)"
changed_when: "'data' in result.json and 'join_instance' in result.json['data'] and result.json['data']['join_instance'] == True"
failed_when: "'errors' in result.json and 'already joined' not in result.content"
```

which is a bit fragile and unreadable.

### Possible solution

Introduce self describing error types, e.g. return not only error message but some constant error identifier
