### ISSUE TITLE
Can't call admin_get_servers over net.box

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1264]
`cartridge.admin_get_servers` uses `cartridge.lua-api.get_topology` function, which returns circular structure.
Here is a structure:
```yaml
servers:
   1:
     uri: localhost:13303
     status: unconfigured
     alias: srv2
     message: 
     uuid: 
   2:
     uri: localhost:13302
     status: unconfigured
     alias: srv1
     message: Unconfigured
     uuid: 
   aaaaaaaa-aaaa-0000-0000-000000000001: &0
     disabled: false
     uuid: aaaaaaaa-aaaa-0000-0000-000000000001
     replicaset: &1
       active_master: *0
       master: *0
       status: healthy
       all_rw: false
       vshard_group: default
       alias: main
       weight: 1
       servers:
       - *0
       roles:
       - vshard-storage
       - vshard-router
       uuid: aaaaaaaa-0000-0000-0000-000000000000
     labels: []
     uri: localhost:13301
     clock_delta: 0.0003355
     message: 
     status: healthy
     priority: 1
     alias: main-1
 replicasets:
   aaaaaaaa-0000-0000-0000-000000000000: *1
```

But `net.box` doesn't support circular structs, so following request fails:
```lua
tarantool> c = nb.connect('localhost:3301')
---
...
tarantool> c:eval('return require("cartridge").admin_get_servers()')
---
- error: Too high nest level - 129
...
```
