### ISSUE TITLE
Stateboard may cause inconsistent leaders map on instances

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1375]
**Steps to reproduce**:

1. Start the cluster with 3 replicasets: r1, r2, s1+s2 (see `replicasets.yml` below). And set up stateful failover (using stateboard).
2. Stop the r2 (e.g. `kill -SIGSTOP $(cat tmp/run/cartridge.srv-2.pid)`).
3. Promote s2 via WebUI.
4. Wait at least 30sec (default `LONGPOLL_TIMEOUT`), then resume the r2.
5. Find the inconsistency in the WebUI of the r2.

![image](https://user-images.githubusercontent.com/2205188/114583768-968a5480-9c8a-11eb-8817-e0f5d3dbcd13.png)

The problem is in the stateboard long-polling algorithm. It persists `longpoll_index` in the `box.session.storage` upon response, but it doesn't mean the client is able to receive the result. In provided reproducer, the `longpoll` results in 

```txt
main/131/cartridge.stateful-failover failover.lua:554 W> "localhost:4401": Timeout exceeded
```

but the connection remains alive. The next longpoll request proceeds with the `longpoll_index` already incremented in the `box.session.storage` and the client never receives the promotion.

To resolve the inconsistency one can repeat _the same_ promotion once again. Or update cluster-wide configuration which will reset the stateboard client. But it's definitely a bug.

<details><summary>replicasets.yml</summary>

```yaml
R1:
  instances:
  - srv-1
  roles:
  - failover-coordinator
  - vshard-router

R2:
  instances:
  - srv-2
  roles:
  - vshard-router
  
S:
  instances:
  - srv-3
  - srv-4
  roles:
  - vshard-storage
  weight: 1
```

</details>
