### ISSUE TITLE
Support unix socket as http server transport

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#1755]
It could be useful for (at least) test purposes.

Our http server supports unix sockets.

> httpd = require('http.server').new(host, port[, { options } ])
host and port must contain:
For unix socket: unix/ and path to socket (for example /tmp/http-server.sock) to bind to. 

However it's completely impossible to use it with cartridge during several reasons:
  - Http port expected to be a number.
  - It's impossible to write simple test on cartridge using unix sockets (but probably luatest is a root of problem here)

In the same way it's possible with pure http server and http client
```yaml
tarantool> http_server = require('http.server').new('unix/', 'socket.sock')
tarantool> http_server:start()
started
tarantool> http_client = require('http.client').new({5})
tarantool> http_client:get('http://localhost/', {unix_socket = './socket.sock'})
GET /
---
- status: 404
  reason: Unknown
  proto:
  - 1
  - 1
  headers:
    content-length: '0'
    server: Tarantool http (tarantool v2.10.0-beta1-18-g2ba6c0667-r442-macos)
    content-type: text/plain; charset=utf-8
    connection: close
...
```

Also it's worth to support unix sockets for box.cfg{listen = ...}. I guess it will allow to parallelize testing of our projects.
