### ISSUE TITLE
Из TNT-569 "check your config's at"

### ISSUE THREAD

**Issue by Thorwinz** [tarantool/cartridge#1847]
Проблема - принесли паппетом кастомные очереди в yaml, и столкнулись, что если кластер не забутстраплен - то кластер не стартует, и ничего не говорит про yaml.
Из-за простого yaml-файлика Cartridge не стартует вообще, и не понятно куда копать 
т.е. само наличие вот такого файлика:
```
/config/tubes.yml
---
ypay_check_transaction: fifottl
ypay_card_unbind: fifottl
ypay_card_sync: fifottl
---
```
ломает всё, а по сообщениям об ошибках и трейсам не понятно, что в этом дело 

Может быть, хотя бы к подобным (ParseConfigError: Missing section:) ошибкам **добавить например** «check your configs at /location/config/whatever.yaml»

версия tarantool-enterprise-1.10.11-0.r470

Шаги воспроизведения:
1. устанавливается tnte 
2. приносятся такие конфиги

```
cluster_cfg:
  box_opts:
    checkpoint_count: 5
    checkpoint_interval: 7200
    log: /logs/tarantool/pxxs-storage.log
    log_level: 6
    memtx_memory: 2147483648
    pid_file: /var/run/tarantool/pxxs-storage.pid
  opts:
    advertise_uri: you-tnx1.p:3302
    alias: you-tnx1@pxxs-storage
    cluster_cookie: x
    http_port: 8081
    roles:
     - sharded_queue.api
      - sharded_queue.storage
      - users_creator
      - cartridge.roles.vshard-router
      - cartridge.roles.vshard-storage
    workdir: /mnt/disk1/tarantool/pxxs-storage
graphite:
  channel_exhaust_interval: 1
  host: graphite.p
  port: 2032
  prefix: you_tarantool.pxxs-storage
```

```
-- /etc/tarantool/instances.enabled/pxxs-storage.lua
 
-- load cluster
local cartridge = require('cartridge')
 
-- load console for admin socket
local console = require('console')
console.listen('/var/run/tarantool/pxxs-storage.control')
 
-- users_creator: role for create users, define it before cluster.cfg
package.preload['users_creator'] = function()
        return {
                init = function()
                        box.schema.user.create('user_ro', {password = 'x', if_not_exists = true})
                        box.schema.user.grant('user_ro', 'read', 'universe', nil, {if_not_exists = true})
                        box.schema.user.create('you', {password = 'x', if_not_exists = true})
                        box.schema.user.grant('you', 'read', 'universe', nil, {if_not_exists = true})
                        box.schema.user.grant('you', 'write', 'universe', nil, {if_not_exists = true})
                        box.schema.user.grant('you', 'execute', 'universe', nil, {if_not_exists = true})
                end
        }
end
 
-- cluster.cfg, https://www.tarantool.io/en/rocks/cluster/1.0/modules/cluster/
-- cartridge.cfg, https://github.com/tarantool/cartridge
cartridge.cfg(
        -- opts
        {
                advertise_uri = 'you-tnx1.p:3302',
                alias = 'you-tnx1@pxxs-storage',
                cluster_cookie = 'x',
                http_port = 8081,
                roles = {'sharded_queue.api', 'sharded_queue.storage', 'users_creator', 'cartridge.roles.vshard-router', 'cartridge.roles.vshard-storage'},
                workdir = '/mnt/disk1/tarantool/pxxs-storage',
        },
        -- box_opts
        {
                checkpoint_count = 5,
                checkpoint_interval = 7200,
                log = '/logs/tarantool/pxxs-storage.log',
                log_level = 6,
                memtx_memory = 2147483648,
                pid_file = '/var/run/tarantool/pxxs-storage.pid',
        }
)
 
-- space-explorer plugin for web-iface
require('space-explorer').init()
```

3. приносится /config/tubes.yml с очередями
4. при запуске инстанса ругается на 37-ую строку конфига из п.4., веб не работает из-за 500-ки запроса в graphql по другой ошибке
5. но если файлик подложить после после бутстрапа, когда уже есть auth.yml           topology.yml   users_acl.yml      vshard_groups.yml  - то норм подсасывает и очереди добавляются
