### ISSUE TITLE
Automatic bootstrap

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#194]
When we use docker-compose or `cartridge start` for local development and testing, it is very tedious to have to go through manual configuration in the UI every time you destroy data directory.

Instead, I suggest an auto-bootstrap that can be performed through configuration file or environment variables. Config file may look like this:

```yaml
default:
  memtx_memory: 12345
  bootstrap_expect: 4
router_1:
  workdir: ./router_1
  http_port: 8081
  advertise_uri: 0.0.0.0:3001
  roles: vshard-router, app
router_2:
  workdir: ./router_2
  http_port: 8082
  advertise_uri: 0.0.0.0:3002
  roles: vshard-router, app
storage_1:
  workdir: ./storage_1
  http_port: 8083
  advertise_uri: 0.0.0.0:3003
  roles: vshard-storage
storage_2:
  workdir: ./storage_2
  http_port: 8084
  advertise_uri: 0.0.0.0:3004
  roles: vshard-storage
```

Look at the `bootstrap_expect` and `roles`. When the number of nodes discovered by membership reaches the value of `bootstrap_expect`, then the first node in alphabetical order will perform cluster bootstrap: join all servers, assign roles to them according to `roles` and perform vshard bootstrap.

In addition to config file it will be possible to pass the same configuration options through environment variables `TARANTOOL_BOOTSTRAP_EXPECT` and `TARANTOOL_ROLES`
