### ISSUE TITLE
[4pt] Replicas weight configuration

### ISSUE THREAD

**Issue by bm0** [tarantool/cartridge#201]
Currently I found no way to configure [weights and zones](https://www.tarantool.io/en/doc/2.2/reference/reference_rock/vshard/vshard_admin/#replica-weights) for replicas and routers.

I think it would be nice to have such a feature in the UI.

**Comment by Fedora7** [comment]
If cartridge can support vshard's zone setting in configure file, that will be a good start.

**Comment by rosik** [comment]
Implementation proposal:

1. Extend `topology.yml` of clusterwide config with a new server property - `zone` (string). Like this:
```yml
-- topology.yml
servers:
  8f22317c-842a-4d3a-9a73-bef841130b03:
    replicaset_uuid: a2b08aaf-ad5c-4c68-9671-bf76ff89b4ad
    zone: "msk"
    uri: "s-a1-msk:3301"
```

Add it to the all related functions - get_topology, edit_topology, etc.

2. Add new clusterwide config section - `zone_distances.yml`. It's content will be similar to the one used in vshard https://www.tarantool.io/en/doc/2.3/reference/reference_rock/vshard/vshard_admin/#replica-weights. E.g.:

```yml
msk: {msk:    0, spb:  620, sib: 2800}
spb: {msk:  620, spb:    0, sib: 3100}
sib: {msk: 2800, spb: 3100, sib:    0}
```
