### ISSUE TITLE
"vshard_group can't be modified" adding replica during configuration

### ISSUE THREAD

**Issue by edam** [tarantool/cartridge#264]
With cartridge 1.1.0, if I try to add a second replica to a replicaset with a`vshard-storage` role, I consistently get this:

```
An error has occurred
replicasets[c51a3e7f-4499-4254-8790-7cdfb1104e9a].vshard_group can't be modified
```

The error does not happen when adding a new replica to a `vshard-router` based replicaset, though. And the error does not happen with cartridge 1.0.0.

For info, here is the error in the application:
```
2019-10-10 11:08:20.823 [26967] main/121/http/127.0.0.1:43688 I> ---
replicasets:
- join_servers:
  - uri: localhost:3402
  uuid: c51a3e7f-4499-4254-8790-7cdfb1104e9a
...

2019-10-10 11:08:20.823 [26967] main/121/http/127.0.0.1:43688 confapplier.lua:714 W> Updating config clusterwide...
2019-10-10 11:08:20.824 [26967] main/121/http/127.0.0.1:43688 graphql.lua:289 E> Invalid config: replicasets[c51a3e7f-4499-4254-8790-7cdfb1104e9a].vshard_group can't be modified
stack traceback:
	...xxx/.rocks/share/tarantool/cartridge/vshard-utils.lua:229: in function <...xxx/.rocks/share/tarantool/cartridge/vshard-utils.lua:184>
	[C]: in function 'xpcall'
	...xxx/.rocks/share/tarantool/errors.lua:139: in function 'validate_config'
	...xxx/.rocks/share/tarantool/cartridge/confapplier.lua:738: in function <...xxx/.rocks/share/tarantool/cartridge/confapplier.lua:711>
	[C]: in function 'xpcall'
	...xxx/.rocks/share/tarantool/errors.lua:139: in function 'pcall'
	...xxx/.rocks/share/tarantool/cartridge/confapplier.lua:854: in function 'patch_clusterwide'
	...xxx/.rocks/share/tarantool/cartridge/admin.lua:774: in function 'edit_topology'
	...xxx/.rocks/share/tarantool/cartridge/admin.lua:861: in function 'call'
	...
	...xxx/.rocks/share/tarantool/cartridge/graphql.lua:286: in function <...xxx/.rocks/share/tarantool/cartridge/graphql.lua:211>
	[C]: in function 'xpcall'
	...xxx/.rocks/share/tarantool/errors.lua:139: in function 'pcall'
	...xxx/.rocks/share/tarantool/cartridge/graphql.lua:302: in function 'sub'
	...xxx/.rocks/share/tarantool/http/server.lua:611: in function <...xxx/.rocks/share/tarantool/http/server.lua:588>
	[C]: in function 'pcall'
	...xxx/.rocks/share/tarantool/http/server.lua:688: in function 'process_client'
	...xxx/.rocks/share/tarantool/http/server.lua:1139: in function <...xxx/.rocks/share/tarantool/http/server.lua:1138>
	[C]: in function 'pcall'
	builtin/socket.lua:1073: in function <builtin/socket.lua:1071>
```

And here's the existing topology:
```
tarantool> cartridge.admin_get_replicasets()
---
- - &0
    all_rw: false
    active_master: &1
      replicaset: *0
      priority: 1
      uri: localhost:3301
      labels: []
      status: healthy
      disabled: false
      message: 
      uuid: 8c8d0079-0402-4c9c-b49b-ab184037601e
    master: *1
    alias: unnamed
    status: healthy
    servers:
    - *1
    uuid: 60f686f1-73dc-416b-bc99-ea49c6d882ce
    roles:
    - vshard-router
    - api
  - &2
    weight: 1
    master: &3
      replicaset: *2
      priority: 1
      uri: localhost:3401
      labels: []
      status: healthy
      disabled: false
      message: 
      uuid: 2376690f-593b-445c-add1-c2f32208c100
    status: healthy
    all_rw: false
    vshard_group: oneandonly
    alias: unnamed
    active_master: *3
    roles:
    - vshard-storage
    - store
    servers:
    - *3
    uuid: c51a3e7f-4499-4254-8790-7cdfb1104e9a
...
```
