### ISSUE TITLE
Application server extensions

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#320]
### Motivation

Nowadays it's impossible to modify app server behavior without re-deploying cartridge app. For demonstrations and some simple cases it would be nice to have an ability to implement a stored procedure or some.

**Comment by rosik** [comment]
### RFC

Cartridge supports another clusterwide config section - `extensions`:
```yaml
extensions:
  - filename: foo.lua
    kind: global_functions
    content: |
      local function get_account(id)
        return box.space.accounts:select({id})
      end

      return {
        get_account = get_account,
      }
```

For the first iteration the only supported type is `global_functions`: all functions returned by this user-defined module are exported as `_G.cartridge_extensions.foo.*`. Later we'll extend supported types with http handlers and other useful stuff.

**Comment by rosik** [comment]
### RFC 2

User-defined stored procedures are part of `ddl`:

```yaml
schema:
  spaces: ...
  functions:
    function_name:
            body: '...'
            is_deterministic: true|false
            is_sandboxed: true|false
            is_multikey: true|false
        ...
```
