### ISSUE TITLE
MktreeError: Error creating directory

### ISSUE THREAD

**Issue by Satbek** [tarantool/cartridge#382]
I use cartridge 1.0.0 and cartridge-cli 1.2.1

If I start app with this instances.yml config

```
eav.api:
  workdir: ./tmp/db/3301/
  http_port: 8081
  advertise_uri: "localhost:3301"

eav.s1-master:
  workdir: ./tmp/db/3302/
  http_port: 8082
  advertise_uri: "localhost:3302"

eav.s1-replica:
  workdir: ./tmp/db/3303/
  http_port: 8083
  advertise_uri: "localhost:3303"

eav.s2-master:
  workdir: ./tmp/db/3304/
  http_port: 8084
  advertise_uri: "localhost:3304"

eav.s2-replica:
  workdir: ./tmp/db/3305/
  http_port: 8085
  advertise_uri: "localhost:3305"
```

i will get this errors on some instances:
```
s1-master | /Users/s.turganbayev/work/eav/init.lua:20: MktreeError: Error creating directory "/Users/s.turganbayev/work/eav/test/stress/tmp/db": File exists
s1-master | stack traceback:
s1-master |     ...ayev/work/eav/.rocks/share/tarantool/cartridge/utils.lua:116: in function 'mktree'
s1-master |     ...urganbayev/work/eav/.rocks/share/tarantool/cartridge.lua:268: in function 'cfg'
s1-master |     /Users/s.turganbayev/work/eav/init.lua:9: in main chunk
s2-replica | Using advertise_uri "localhost:3305"
```

I think this is because of race-condition between tarantool instances. And cartridge-cli may create workdirs for instances before starting them.
