### ISSUE TITLE
Design extension role

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#454]
## The task
We need to build the special extension role which will let users, write code and match user-functions like an HTTP server endpoint or just match function as a stored procedure. This role will let users simply write some functionality (maybe, distributed) and pass it externally.

**Comment by artur-barsegyan** [comment]
The first iteration should be without any logs: only status codes (from HTTP) and stack trace.

For extension sandbox, we can create an external directory with one `config.yml` and some Lua files with code (as users want).

**extension folder:**
- config.yml
- customers.lua
- ...

I suggest to let to separate extensions on some modules, where any module can contain any kind of objects:
* storage procedures (available by net.box)
* HTTP route

*customers.lua:*
```lua
  local http_methods = {}
  local storage_procedures = {}
  
  local function storage_procedures.shard_put_customer(customer)
    ...
  end
  
  local function storage_procedures.get_customer_by_id(id)
    ...
  end
  
  local function storage_procedures.put_customer(customer)
    local bucket_id = vshard.router.bucket_id(customer.id)
    local ... = vshard.router.call('shard_put_customer', bucket_id, 'write', customer, ...)
    
    ...
  end
  
  local function http_methods.my_handler_name(req)
    local req_json = req:json()
    local id = req_json.id
    
    local bucket_id = vshard.router.bucket_id(id)
    local response = vshard.router.call('get_customer_by_id', bucket_id, 'read', id, ...)
  
    return req:render({ status = 200, json = response })
  end
  
  return {
      http_methods = http_methods,
      storage_procedures = storage_procedures,
  }
```

*config.yml:*
```yaml
---
http:
  getCustomerById:
    request_type: 'GET'
    route: '/getCustomer'
      
storage_procedures:
  put_customer:
    eligible_users:
      - admin
      - staff

  shard_put_customer:
    eligible_users:
      - admin
      - staff
 ```
